#!/bin/sh
 
# JSHint validation before commit.

files=$(git diff --cached --name-only --diff-filter=ACM | grep ".js$")
if [ "$files" = "" ]; then 
    exit 0 
fi
 
pass=true
 
for file in ${files}; do
    result=$(jshint ${file})
    if [ $? == 0 ]; then
        echo -e "\033[32mJSHint Passed: ${file}\033[0m"
    else
        echo -e "\033[31mJSHint Failed: ${file}\033[0m"
        echo -e "\033[31m$(jshint ${file} | sed '$d' | sed '$d')\033[0m\n"
        pass=false
    fi
done
 
if ! $pass; then
    echo -e "\033[41mCOMMIT FAILED:\033[0m Please fix the JSHint errors and try again.\n"
    exit 1
fi
